### ISSUE TITLE
Missing support for 10.70FW version

### ISSUE THREAD

**Issue by dotur911** [DrYenyen/PPPwn-Tinker-GUI#1]
Please,if you could add this version in app. Thank you!

**Comment by DrYenyen** [comment]
> Please,if you could add this version in app. Thank you!

I'm releasing a new version of the GUI tonight or tomorrow I'll be sure to add it in thank you for bringing it to my attention I have the bins there but not the option in the GUI.

**Comment by dotur911** [comment]
I am on 10.70, i will be honnored to help testing or somehing else. Thaank you for work.
PS: GoldHen does not EXISTS for 10.70 as you stated there is in package !

**Comment by DrYenyen** [comment]
> I am on 10.70, i will be honnored to help testing or somehing else. Thaank you for work. PS: GoldHen does not EXISTS for 10.70 as you stated there is in package !

[Tinker 2.0 released and has 10.70 support](https://github.com/DrYenyen/PPPwn-Tinker-GUI/releases/tag/2.0)
